import os

print("Downloading updated repository as temporary files")
os.system("git clone https://github.com/liamcolangelo/BASIC.git tempBASIC")
print("Copying new files")
os.system("sudo cp tempBASIC/update.py /usr/bin/basic/update.py")
os.system("sudo cp tempBASIC/install.py /usr/bin/basic/install.py")
os.system("sudo cp tempBASIC/uninstall.py /usr/bin/basic/uninstall.py")
os.system("sudo cp tempBASIC/runBasic.py /usr/bin/basic/runBasic.py")
os.system("sudo cp tempBASIC/README.md /usr/bin/basic/README.md")
os.system("sudo cp tempBASIC/GUESSANUMBER.BAS /usr/bin/basic/GUESSANUMBER.BAS")
print("Removing temporary files")
os.system("cd ..")
os.system("rm -r -f tempBASIC")
print("Finished")